import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>hamy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/gradient-icon.ico" />
      </Head>

      <main className={styles.main}>
        <h4 className={styles.title}>{`hamy's art`}</h4>
      </main>
    </div>
  );
};

export default Home;
